INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (8, N'Algebra', 6, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (9, N'Calculus', 6, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (10, N'Computer Systems Arhitecture', 6, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (11, N'Fundamentals of Programming', 6, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (12, N'Computational Logic', 6, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (13, N'Sports 1', 2, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (14, N'Operating Systems', 5, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (15, N'Object Oriented Programming', 5, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (16, N'Data Structures and Algorithms', 5, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (17, N'Geometry', 5, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (18, N'Dynamical Systems', 5, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (19, N'Graph Algorithms', 5, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (20, N'Sports 2', 2, 0, 6);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (21, N'Advanced Programming Methods', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (22, N'Computer Networks', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (23, N'Databases', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (24, N'Logic and Functional Programming', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (25, N'Probability and Statisctics', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (26, N'English 1', 3, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (27, N'Software Engineering', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (28, N'Database Management Systems', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (29, N'Artificial Intelligence', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (30, N'Web Programming', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (31, N'Systems for Design and Implementation', 6, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (32, N'English 2', 3, 0, 7);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (33, N'Parallel and Distribuited Programming', 5, 0, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (34, N'Formal Languages and Compiler Design', 5, 0, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (35, N'Mobile Application Programming', 4, 0, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (36, N'Internship', 6, 0, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (37, N'Software Systems Verification and Validation', 7, 0, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (38, N'Numerical Calculus', 7, 0, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (39, N'Elaboration of the bachelor thesis', 3, 0, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (40, N'Public-key Cryptography', 4, 1, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (41, N'Robotic Process Automation', 4, 1, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (42, N'Audio-Video Data Processing', 4, 1, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (43, N'Computer Vision and Deep Learning', 4, 1, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (44, N'Virtual Reality', 4, 1, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (45, N'Cloud Application Arhitechture', 4, 1, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (46, N'Affective Computing', 4, 1, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (47, N'Android Things', 5, 1, 8);
INSERT INTO AcademicInfo.dbo.Courses (ID, Name, NoOfCredits, IsOptional, CurriculumID) VALUES (48, N'New Media', 5, 1, 8);
