USE Planner2
GO

ALTER DATABASE Planner2 SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Email SET Subject='Chicken Wings' WHERE Id=17
WAITFOR DELAY '00:00:05'
COMMIT TRAN

--ALTER DATABASE Planner2 SET ALLOW_SNAPSHOT_ISOLATION OFF
--UPDATE Email SET Subject='Crispy Strips' WHERE Id=17
--SELECT * FROM Email