//
// Created by Alex Campean on 10.06.2022.
//

#ifndef EXAM_PRACTICE_QUESTION_ANSWERS_SEARCHWIDGET_H
#define EXAM_PRACTICE_QUESTION_ANSWERS_SEARCHWIDGET_H


class SearchWidget {

};


#endif //EXAM_PRACTICE_QUESTION_ANSWERS_SEARCHWIDGET_H
