DOMAIN_MIN = -10
DOMAIN_MAX = 10

INPUT_SIZE = 1000
NUMBER_OF_DIMENSIONS = 2
NUMBER_OF_HIDDEN_LAYERS = 42
OUTPUT_SIZE = 1

# DATA SET
MODEL_PATH = "myNetwork.pt"
TRAINED_MODEL_PATH = "myTrainedNetwork.pt"
DATA_PATH = "mydataset.dat"
